### ISSUE TITLE
Not all files are on GitHub?

### ISSUE THREAD

**Issue by Razunter** [Sheep-y/BattleTech_Mods#5]
Trying to compile the mod, but project missing Properties\AssemblyInfo.cs and src\LineOfFire.cs
Currently v1.0.1 does not cap accuracy between 0 and 100 as it should, trying to figure this out.

**Comment by Sheep-y** [comment]
Thanks for the report. AssemblyInfo has been added. LineOfFire is not currently used and its reference may be safely removed.

**Comment by Sheep-y** [comment]
Relevant code is in RollCorrection.cs

**Comment by Razunter** [comment]
Yep. Compiled fine, getting `Uncached hit chance reversal from NaN, diff: NaN` in log, will look into it later. But it's unlikely that I'll find anything.
