### ISSUE TITLE
Add hit chance overflow correction

### ISSUE THREAD

**Issue by Razunter** [Sheep-y/BattleTech_Mods#6]
Looks like modded hit chance modifiers can go crazy and cause overflow. Scope of this mod fits perfectly for a fix.

Raw and not properly tested code:
```
Patch(typeof(ToHit), "GetUMChance", new Type[] { typeof(float), typeof(float) }, "OverrideGetUMChance", null);
```

```
public static bool OverrideGetUMChance(ToHit __instance, ref float __result, CombatGameState ___combat, float baseChance, float totalModifiers)
        {
            try
            {
                float num;
                if (___combat.Constants.ToHit.ToHitUseSteppedAlgorithm)
                {
                    num = __instance.GetSteppedValue(baseChance, totalModifiers);
                }
                else
                {
                    float toHitModifierDivisor = ___combat.Constants.ToHit.ToHitModifierDivisor;
                    float newTotalModifiers = -totalModifiers >= toHitModifierDivisor ? -toHitModifierDivisor + 1 : totalModifiers;
                    float num2 = 1f - newTotalModifiers / (newTotalModifiers + toHitModifierDivisor);
                    num = baseChance * num2;
                }
                num += 0.025f;
                num -= num % 0.05f;
                num = Mathf.Min(0.95f, num);
                __result = Mathf.Max(0.05f, num);
                return false;
            }
            catch (Exception ex) { return Log(ex); }
        }
```

**Comment by Sheep-y** [comment]
Thanks for code! Will review code path when I can. A few events happened that is currently putting a big penalty on my Tech Level. Siting in hospital right now…

**Comment by LadyAlekto** [comment]
Hope it's not too bad and you get well soon :)

**Comment by Sheep-y** [comment]
Ok, checked the code. The reason I don't get NaN is because ToHitUseSteppedAlgorithm is default true, so I never see those unless a mod change it.

ToHitModifierDivisor is 10 by default. When total modifier is -10, it will becomes NaN.  Below -10, and it will become negative.  ToHitUseSteppedAlgorithm seems to simply cap the modifier at 10.

**Comment by Sheep-y** [comment]
Ok, I think NaN and weird numbers will happen only if `Constants.ResolutionConstants.AllowTotalNegativeModifier` is true AND `Constants.ToHit.ToHitUseSteppedAlgorithm` is false AND totalModifiers is, well, very negative.  The original algorithm throws NaN when totalModifier is -10 and always make the accuracy negative beyond that point.

Razunter's code an kill the NaN and negative, but will also cause accuracy to shot through the roof that it is meaningless beyond -2 or -3.   Working on an improved formula, then will compile a preview build for you two to test.

**Comment by LadyAlekto** [comment]
Yes, thats actually currently an issue

Looking forward to it because without the AllowTotalNegativeModifier true the penaltys dont apply as well as they should

**Comment by Sheep-y** [comment]
Prototyping the following formula.

Diminishing Bonus = 2-Base^(Bonus/Divisor), Default 2-0.75^(Bonus/6).
Example: +3 Bonus @ 80% Base ToHit = 113% x 80% = 91% Hit

Diminishing Penalty = Base^(Penalty/Divisor), Default 0.85^(Penalty/1.5)
Example: +6 Penalty @ 80% Base ToHit = 52% x 80% = 41% Hit

**Comment by LadyAlekto** [comment]
I like the idea of diminishing returns (especially above the floor value, which i really dont like)

Both together can really help to smooth out extreme ranges of bonus and penalty's to hits

How would you distingusih between bonus and penalty because for the games logic its just a negative float_add

*shouldnt check on gits when half melted*

**Comment by Sheep-y** [comment]
The game has two ways to handle modifiers: either simple addition, or a diminishing return algorithm. The switch is `ToHitUseSteppedAlgorithm`.

The original algorithn works pretty well on penalties, but will be bugged on -10 modifier (bonus) or more.  So I tried to fix it by replacing the formula.

It is easy for the code to distinguish penalty and bonus: penalty is positive, while bonus is negative. Given the abundant nature of penalties, the same curve does't work well on both, so I split the two pretty early.

I've only played two skirmishs and it does not work as well as expected. Initial drop off is still too big. I may use a simpler approach by reversing the original formula on bonus instead. But you can still test it with a high hit bonus and confirm whether you are still seeing NaN.

**Comment by Sheep-y** [comment]
Turns out the original formula has even worse dropoff / flexibility, so I've tuned my formula to match default stepped chance better and call it a day.

"DiminishingPenaltyPowerBase": 0.8,
"DiminishingPenaltyPowerDivisor": 3.3,

**Comment by Razunter** [comment]
@LadyAlekto yep, it replaces my "fix"

**Comment by LadyAlekto** [comment]
Sooo i finally got around to update it and it just kept crashing my game

**Comment by Sheep-y** [comment]
I only have the game on Steam but it is almost vanilla with just two more very small mods. The parts that I touched so far does not involve any Steam functions.

I assume it didn't crash with last mod release (mod v1.0.1). Are there any rrrors being logged in mod log or modtek log?  If not the next step is to disable other mods and see if it works alone. If it does then there is a conflict :(

**Comment by LadyAlekto** [comment]
It triggered steams soft drm

NullReferenceException: Object reference not set to an instance of an object
at BattleTech.SteamManager.get_Initialized () [0x00000] in <filename unknown>:0
at BattleTech.Achievements.ISteamAchievments.InitializeBackend (System.Collections.Generic.Dictionary`2 achievements) [0x00000] in <filename unknown>:0
at BattleTech.Achievements.BattleTechAchievmentsAPI..ctor (BattleTech.GameInstance gameInstance) [0x00000] in <filename unknown>:0
at BattleTech.GameInstance..ctor () [0x00000] in <filename unknown>:0
at BattleTech.UnityGameInstance.Reset () [0x00000] in <filename unknown>:0
at BattleTech.UnityGameInstance.Awake () [0x00000] in <filename unknown>:0

System.NullReferenceException: Object reference not set to an instance of an object
at BattleTech.UnityGameInstance.<OnInternetConnectivityResult>m__1 (Boolean callbackSuccess, System.Net.IPAddress ipAddress) [0x00000] in <filename unknown>:0
at BattleTech.Network.NetworkUtilities+<GetExternalIPAddressRoutine>c__Iterator0.MoveNext () [0x00000] in <filename unknown>:0

Didn't saw any other errors and the only fix was to completely nuke and reinstall my game and downgrade to 101

Admittedly didnt dare try the remove bits by bits approach (i would assume the melee mover having a conflict, and i almost got janxious to add a similar function with failstate into his charlesb melee package ;))

Only other time i saw this error was with gog compiled dll's 

And this complicated everything even more

**Comment by LadyAlekto** [comment]
Another thought, could it be an incompatibility with this private release of btml

Ill test regenerating to a "lesser version" and see what happens (i dont wanna loose my loading screen :'( )

**Comment by Razunter** [comment]
Just to note, @LadyAlekto uses my compile of fresher version than beta. But it works fine for me...

**Comment by Razunter** [comment]
It is related to new BTML\ModTek. Looks like it bugs out because of early CacheCombatState() in Init(), fails on UnityGameInstance.BattleTechGame.

**Comment by Sheep-y** [comment]
Yes. That is not a good idea, as we have now seen.  Fortunately I have been moving them away to eliminate the early dependency, and it looks like the early CacheCombatState() has been made a legacy code that can be safely removed.

A new preview build is released.  I am using latest BTML and ModTek, both ver 0.2.3, and you seems to be a quite capable coder, so I'll leave the compatibility test for you. ;)

**Comment by Razunter** [comment]
Thx! Works now. And I'm a terrible coder, it's just bugs tend to like me.
LoS looks nice too.
BTW, since you're mastercrafting Legenrary Mod of Rule-Them-All, only thing needed to replace [MeleeMover](https://github.com/Morphyum/MeleeMover) is
> sprintRangeMelee | bool | default true | Melee now can happen at sprint range.

**Comment by Sheep-y** [comment]
Doing reasonably well for my first game mod ever, no? XD
I don't intentionally mimic other mod's features, but I don't see a reason to not add that at this stage lol.  Wanted to do called melee first but called shot proves to be a pretty inflexible design that involves many hard-coding.  Possible but will take time.

Anyway, I'll close this bug for now since it's two pre-releases with the net bonus feature coded, NaN fixed, and so far I haven't found other problems.
